// NEWS ACTIONS

export const FETCH_NEWS_INIT = 'FETCH_NEWS_INIT'
export const FETCH_NEWS_SUCCESS = 'FETCH_NEWS_SUCCESS'
export const FETCH_NEWS_FAILURE = 'FETCH_NEWS_FAILURE'

export const FETCH_NEWSITEM_INIT = 'FETCH_NEWSITEM_INIT'
export const FETCH_NEWSITEM_SUCCESS = 'FETCH_NEWSITEM_SUCCESS'
export const FETCH_NEWSITEM_FAILURE = 'FETCH_NEWSITEM_FAILURE'

export const SAVE_NEWS_INIT = 'SAVE_NEWS_INIT'
export const SAVE_NEWS_SUCCESS = 'SAVE_NEWS_SUCCESS'
export const SAVE_NEWS_FAILURE = 'SAVE_NEWS_FAILURE'

